version: '3.3'

networks:
  sttm-net:
    driver: bridge

services:
  sttm-db:
    image: postgres:12.0
    networks:
      - sttm-net
    volumes:
      - ./db_schema/sql_scripts/database_schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db_schema/sql_scripts/data/init.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB:       schooltimetabledb
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: password

  sttm-app:
    build: bootApplication/
    depends_on:
      - sttm-db
    networks:
      - sttm-net
    ports:
      - "8686:8686"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sttm-db:5432/schooltimetabledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

#  sttm-ui:
#    build: ui
#    depends_on:
#      - sttm-app
#    networks:
#      - sttm-net
#    ports:
#      - "4200:4200"
#    environment:
#      SERVER_URL: 'http://your.ip:8080'
